[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_MODE = "production"
  CI = "true"

[context.deploy-preview.environment]
  VITE_APP_MODE = "staging"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
