[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_MODE = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
