[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  OPENAI_API_KEY = "@openai_api_key" # Usa variabili d'ambiente

[dev]
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
